# CI on Unix OS 
# Separated from main CI matrix to reduce churn on failures due to infra
name: AIX CI

on: 
  workflow_dispatch:
  push:
    branches:
 #temporarily disabled due to polarhome outage
      - masterdisabled
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

#jobs:
  # SSH into AIX server and run test on AIX 7.1
  # Configured to pull latest from oshi master branch
  # To test on a PR, log into the aix server and create a new branch
  testaix:
    runs-on: ubuntu-latest
    name: Test JDK 8, aix
    steps:
    - name: Test in AIX
      uses: appleboy/ssh-action@master    
      with:
        host: gate.polarhome.com
        username: oshi
        password: ${{ secrets.AIX_OSHI_PW }}
        port: 775
        script_stop: true
        command_timeout: 75m
        script: |
          source .profile
          source .bashrc
          cd ~/git/oshi
          git checkout master
          git reset --hard HEAD~2
          git pull
          mvn clean test -B -Djacoco.skip=true

          