# CI on Unix OS 
# Separated from main CI matrix to reduce churn on failures due to infra
name: Solaris CI

on: 
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

jobs:
  # Runs current branch on Solaris 11.4 in a VM
  testsolaris:
    runs-on: ubuntu-latest
    name: Test JDK 8, solaris
    steps:
    - name: Test in Solaris
      uses: appleboy/ssh-action@master    
      with:
        host: ${{ secrets.SOLARIS_OSHI_DOMAIN }}
        username: oshi
        password: ${{ secrets.SOLARIS_OSHI_PW }}
        port: 10061
        script_stop: true
        command_timeout: 15m
        script: |
          cd ~/git/oshi
          git checkout master
          git reset --hard HEAD~2
          git pull
          mvn clean test -B -Djacoco.skip=true
                    